### ISSUE TITLE
[d3d9] NEKOPARA Vol. 0, 1, 2 (385800, 333600, 420110) - Non-static character models (E-mote) are partially or completely transparent.

### ISSUE THREAD

**Issue by ZereoX** [doitsujin/dxvk#1647]
### Description:
This was reported by a user on the Proton Issue Tracker: https://github.com/ValveSoftware/Proton/issues/180#issuecomment-611259828

In **_NEKOPARA Vol. 0, 1, 2_** (385800, 333600, 420110) non-static character models (E-mote) are partially or completely transparent.

This issue occurs on both Proton 5.0-7 and Windows using DXVK 1.7 or master (5558460). Issue is not present on WineD3D or Native Windows D3D. The issue however appears when replaying a Native Windows D3D apitrace in qapitrace on Windows.

| DXVK | WineD3D / Native |
| ---- | ---- |
|![NEKOPARA Vol  1 - 333600 - 3D Portrait DXVK](https://user-images.githubusercontent.com/761853/83542239-ad87e400-a4c8-11ea-84f2-8cdb825f4f1f.png)|![NEKOPARA Vol  1 - 333600 - 3D Portrait WineD3D](https://user-images.githubusercontent.com/761853/83542249-b24c9800-a4c8-11ea-8df5-3a72a81a1ad3.png)|

Please let me know if any additional information is required or if additional testing is needed.

#### Notes
- E-mote characters appear corretly in [NEKOPARA Vol. 3](https://store.steampowered.com/app/602520/NEKOPARA_Vol_3/) & [Extra](https://store.steampowered.com/app/899970/NEKOPARA_Extra/).

### Software information
[NEKOPARA Vol. 0](https://store.steampowered.com/app/385800/NEKOPARA_Vol_0/) (385800)
[NEKOPARA Vol. 1](https://store.steampowered.com/app/333600/NEKOPARA_Vol_1/) (333600)
[NEKOPARA Vol. 2](https://store.steampowered.com/app/420110/NEKOPARA_Vol_2/) (420110)

### System information
OS: Ubuntu 18.04 / Windows 10 Pro 1909
GPU: Radeon RX 580 / Nvidia GeForce GTX 1060
Beta Drivers: 20.2\~git2006011930.7c793a\~oibaf\~e / 440.66.15 (443.24 for Windows)
Stable Drivers: 20.0.7\~kisak1\~b / 440.82-0ubuntu0~0.18.04.1 (446.14 for Windows)
Wine version: Proton 5.0-7
DXVK version: 1.7 / Master (5558460)

### Apitrace file
- NEKOPARA Vol. 1: https://drive.google.com/file/d/1TXOTw5P5H6NSz05ymoX5LULmxAnWGFXt/view?usp=sharing

### Log files
d3d9.log: [nekopara_vol1_d3d9.log](https://github.com/doitsujin/dxvk/files/4718305/nekopara_vol1_d3d9.log)

### Tested froggi.es builds:
master - 5558460 (❌) - [#1309](https://git.froggi.es/doitsujin/dxvk/-/jobs/1309)
1.7 - 2e37825 (❌) - [#1286](https://git.froggi.es/doitsujin/dxvk/-/jobs/1286)
1.6.1 - dbc9f40 (❌) - [#1261](https://git.froggi.es/doitsujin/dxvk/-/jobs/1261)
1.5.5 - 1e426cd (❌) - [#1178](https://git.froggi.es/doitsujin/dxvk/-/jobs/1178)
1.5.0 - 3cdae3a (❌) - [#1044](https://git.froggi.es/doitsujin/dxvk/-/jobs/1044)

**Comment by Joshua-Ashton** [comment]
This is a game bug, but I can work around it.

It's entirely stupid. The game locks mip 1 then unlocks mip 0 and expects it to upload -- so then when it renders it does mip filtering between 0 and 1 and 1 hasn't been uploaded which makes this funny transparent catgirl.

**Comment by Joshua-Ashton** [comment]
Should be fixed now!

**Comment by ZereoX** [comment]
Hi @Joshua-Ashton,

I retested on Vol.0 (since you have that game) and the issue is fixed by d39cf31 / b658cae however fa988be appears to break it again to a lesser extent:

| fa988be | b658cae | WineD3D |
| ------ | ------ | ------ |
|![DXVK](https://user-images.githubusercontent.com/761853/83906694-0c03cb00-a732-11ea-9155-7ff89f7011c0.png)|![DXVK-326f6c2](https://user-images.githubusercontent.com/761853/83906858-5422ed80-a732-11ea-9dda-a07b5486cf70.png)|![WINED3D](https://user-images.githubusercontent.com/761853/83906717-16be6000-a732-11ea-8293-1b9a9f432d20.png)|
|![DXVK-2](https://user-images.githubusercontent.com/761853/83906734-1b831400-a732-11ea-9722-749c8aa31d65.png)|![DXVK-2-326f6c2](https://user-images.githubusercontent.com/761853/83906751-263da900-a732-11ea-835e-2dce64849e4c.png)|![WINED3D-2](https://user-images.githubusercontent.com/761853/83906758-2a69c680-a732-11ea-9d0f-d83298618ad4.png)|

Overall transparency is much higher with fa988be, when characters tilt their heads some transparent layering effects can also be seen.

![DXVK-Highlight](https://user-images.githubusercontent.com/761853/83907491-79642b80-a733-11ea-9bc2-8a4dd9634957.png)

This was tested on Proton 5.0-8-RC1 w/ DXVK Build [#1311](https://git.froggi.es/doitsujin/dxvk/-/jobs/1311) and [#1310](https://git.froggi.es/doitsujin/dxvk/-/jobs/1310)

**Comment by K0bin** [comment]
Could you try it with my branch: https://github.com/K0bin/dxvk/tree/mark-dirty-in-lock?

**Comment by ZereoX** [comment]
I confirmed that all 3 Nekopara titles (Vol. 0, 1, 2) are not displaying correctly when using DXVK master (291f7e0).

Closing... Thanks.

(Sorry for the delay I was on vacation this past week.)

**Comment by K0bin** [comment]
> I confirmed that all 3 Nekopara titles (Vol. 0, 1, 2) are not displaying correctly when using DXVK master

Are they still broken or did you mean to write 'are **now** displaying correctly'?

**Comment by ZereoX** [comment]
@K0bin Yeah, sorry that was a typo. They are indeed rendering correctly. I'll edit my comment to make the correction. Thanks.
