### ISSUE TITLE
Pop-in artifact in Assassin's Creed: Odyssey

### ISSUE THREAD

**Issue by yokem55** [doitsujin/dxvk#928]
There seems to be a pop-in rendering bug in AC: Odyssey with some structures. Demonstrated in the following video:
https://youtu.be/L3CpnHNOj0Y

### Software information
Assassin's Creed: Odyssey - 
[ACOdyssey.ini.txt](https://github.com/doitsujin/dxvk/files/2883613/ACOdyssey.ini.txt)

### System information
- GPU: Nvidia RTX 2080
- Driver: 418.30.0
- Wine version: 'tkg-protonified-4.1', esync enabled. 
- DXVK version: 0.96

### Apitrace file(s)
- Unable to create demonstrating the issue. The game crashes while the save game is loading with the API trace active. (enabled by placing the DLL's along the game's executable). I'm happy to try a different method to get the trace if one is known for this game. 

### Log files
- d3d11.log:
[ACOdyssey_d3d11.log](https://github.com/doitsujin/dxvk/files/2883685/ACOdyssey_d3d11.log)

- dxgi.log: 
[ACOdyssey_dxgi.log](https://github.com/doitsujin/dxvk/files/2883686/ACOdyssey_dxgi.log)

**Comment by doitsujin** [comment]
Can't reproduce. Can you please test whether this happens with the latest Nvidia Vulkan beta driver as well?

**Comment by ah-** [comment]
I've tried to reproduce this on Proton 3.16-7 and 418.31.03 on both max and medium settings but couldn't spot anything like it. Maybe this got fixed?

**Comment by yokem55** [comment]
I can confirm this is indeed fixed with the 418.31.03 drivers. Thank you.

**Comment by tsalwierz** [comment]
Issue persists on DXVK 1.0, Wine 4.3 and 418.43 nvidia drivers.
![creed](https://user-images.githubusercontent.com/7935624/54081121-17a8dd80-42b4-11e9-991b-76894eb81375.jpeg)

**Comment by yaffa7** [comment]
This game has been working flawlessly for the past couple months. But a an upgrade to Nvidia drivers 4.18.43 and Vulkan 1.1.95 has immediately caused the issue described here to start happening.

    

- GPU: Nvidia RTX 1080
- Driver: 418.43.0
- Wine version: 'tkg-4.2'
- DXVK version: 1.0

Video: https://youtu.be/l-kATwTDhE0

Will provide logs as soon as i can

@doitsujin Should i start a new issue for this or continue this thread?

**Comment by doitsujin** [comment]
@yaffa7 this is not a DXVK bug and it is my understanding that this issue is fixed in the Nvidia beta drivers. Please use that for now.

**Comment by yokem55** [comment]
This issue has returned again in the latest nvidia vulkan beta (418.49.04). Reverting to the previous vulkan beta (418.31.03) fixes it.

**Comment by tsalwierz** [comment]
Confirmed, bug is on 418.49.04.

**Comment by yokem55** [comment]
Back on 481.49.04 to run DXVK 1.1, it appears to be that this bug is now resolved.

**Comment by yokem55** [comment]
Still present in the 418.52.03 vulkan beta with DXVK 1.0.3.
Reported to Nvidia here - 
https://devtalk.nvidia.com/default/topic/1050175/linux/pop-in-corruption-with-assassins-creed-odyssey-running-under-wine-dxvk/post/5329905/

**Comment by Vash63** [comment]
![20190422234133_1](https://user-images.githubusercontent.com/3086017/56533801-b03fa800-6558-11e9-8cc6-40d1058e0a51.jpg)

Screenshot of the issue with the latest Vulkan dev drivers (418.52.05)

**Comment by Vash63** [comment]
Not sure if this is expected based on branch dates or something but I can also duplicate this on 430.09

**Comment by chaitan3** [comment]
Duplicated on 430.14. Downgrading the nvidia driver to 415.27 fixes the issue.

**Comment by Vash63** [comment]
I can duplicate this on yesterday's new 418.52.07 drivers as well.

**Comment by Vash63** [comment]
I can no longer duplicate this with 418.52.10! Seems they fixed it.

**Comment by chui2ch** [comment]
It seems to be fixed in the new 430.26 driver as well as the beta.
